---
- hosts: all

  tasks:

  - name: Upgrade all packages
    ansible.builtin.apt:
      upgrade: yes
      update_cache: true
      cache_valid_time: 3600
      autoremove: yes
      autoclean: yes
      clean: yes
